version: '1'
services:
  costumer-order-services:
    container_name: costumer-order-services
    image: costumer_order_services:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - JWT_KEYS=${JWT_KEYS}
    tty: true
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    ports:
      - "8081:8080"
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
volumes:
  pgdata: {}